name: MRHC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: ./script/setup.sh
    - name: mrhc
      run: make
    - name: setup test
      run: ./script/setup_test.sh
    - name: start vnc
      run: ./test/start_vnc.sh
    - name: mrhc test
      run: make test
    - name: stop vnc
      run: ./test/stop_vnc.sh
    - uses: actions/upload-artifact@v1
      with:
        name: mrhc.jpeg
        path: /tmp/mrhc.jpeg
