name: MRHC

on:
  push:
    branches: [ master, feature/ci_pass ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt-get update
    - name: apache
      run: sudo apt install apache2-dev 
    - name: opencv
      run: sudo apt install libopencv-dev
    - name: google test
      run: |
        sudo apt install cmake
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest/
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib
    - name: mrhc
      run: make
