name: MRHC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: libpcre3-dev
      run: sudo apt install libpcre3-dev
    - name: build-essential
      run: sudo apt install build-essential
    - name: libapr1-dev
      run: sudo apt install libapr1-dev
    - name: libaprutil1-dev
      run: sudo apt install libaprutil1-dev
    - name: apache2-dev
      run: sudo apt install apache2-dev 
    - name: opencv
      run: sudo apt install libopencv-dev

